baseurl = "https://heimatverein-niederjosbach.de/"
languageCode = "de-de"
title = "Niederjosbacher Heimat- und Geschichtsverein 2007 e.V."
theme = "heimatverein-niederjosbach"
pluralizelisttitles = "false"
paginate = 12

[[menu.main]]
  name = "Home"
  weight = -110
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Aktuelles"
  weight = -109
  identifier = "aktuelles"
  url = "/aktuelles"

[[menu.main]]
  name = "Termine"
  weight = -108
  identifier = "termine"
  url = "/termine"

[[menu.main]]
  name = "Galerie"
  weight = -107
  identifier = "galerie"
  url = "/galerie"

[[menu.main]]
  name = "Niederjosbach"
  weight = -106
  identifier = "niederjosbach"
  url = "/niederjosbach"

[[menu.main]]
    name = "Geschichte"
    weight = 0
    identifier = "geschichte"
    url = "https://heimatverein-niederjosbach.de/files/niederjosbach/geschichte.pdf"
    parent = "niederjosbach"

[[menu.main]]
    name = "Geschichte der Schule"
    weight = 1
    identifier = "geschichte-der-schule"
    url = "https://heimatverein-niederjosbach.de/files/niederjosbach/dorfschule_zu_niederjosbach.pdf"
    parent = "niederjosbach"

[[menu.main]]
  name = "Verein"
  weight = -105
  identifier = "verein"
  url = "/verein"

[[menu.main]]
    name = "Vorstand"
    weight = 1
    identifier = "vorstand"
    url = "/verein/vorstand"
    parent = "verein"

[[menu.main]]
    name = "Beitrittserklärung"
    weight = 2
    identifier = "beitrittserklaerung"
    url = "https://heimatverein-niederjosbach.de/files/verein/beitrittserklaerung_nhgv.pdf"
    parent = "verein"

[[menu.main]]
    name = "Satzung"
    weight = 2
    identifier = "satzung"
    url = "https://heimatverein-niederjosbach.de/files/verein/satzung.pdf"
    parent = "verein"

[[menu.main]]
  name = "Gedichte & Erzählungen"
  weight = -104
  identifier = "gedichte-erzaehlungen"
  url = "/gedichte-erzaehlungen"

[[menu.main]]
  name = "Kontakt"
  weight = -103
  identifier = "kontakt"
  url = "/kontakt"

[[menu.main]]
  name = "Impressum"
  weight = -102
  identifier = "impressum"
  url = "/impressum"