backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/files/uploads" # Media files will be stored in the repo under static/files/uploads
public_folder: "/files/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "termine" # Used in routes, e.g., /admin/collections/blog
    label: "Termine 2019" # Used in the UI
    folder: "content/termine/2019" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{month}}_{{day}}_{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Veranstaltung", name: "title", widget: "string"}
      - {label: "Event date", name: "date", dateFormat: "DD.MM.YYYY", timeFormat: "HH:mm", widget: "datetime"}
      - {label: "Verein", name: "verein", widget: "select", options: ["Heimatverein", "Katholische Kirche", "Gesangverein Taunusliebe", "Gesangverein Sängerlust", "Obst- und Gartenbauverein", "Freiwillige Feuerwehr", "Schützenverein Bremthal / Niederjosbach", "GCC", "TuS Niederjosbach", "Basarteam Niederjosbach", "Hobbykünstler", "Katholischer Kirchenchor", "Kirchengemeinde", "Vereinsring Niederjosbach", "KiTa Niederjosbach", "FFW Niederjosbach", "Vereinsring", "Vereinsring Njb.", "Vereinsring (insb. Sängerlust) + Ortsvorsteherin", "OGV Niederjosbach", "GCC 1981 e.V.", "Kath. Kirchenchor", "TuS Niederjosbach, Abtlg. Fußball", "Stadt + Kirchengemeinden", "TuS Niederjosbach, Abt. Fussball", "Förderverein St. Michael", "Stadt Eppstein+GCC"], default: ["Heimatverein"]}
      - {label: "Ort", name: "ort", widget: "string"}
  - name: "aktuelles" # Used in routes, e.g., /admin/collections/blog
    label: "Aktuelles 2019" # Used in the UI
    folder: "content/aktuelles/2019" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", dateFormat: "DD.MM.YYYY", timeFormat: "HH:mm", widget: "datetime"}
      - {label: "Galerie", name: "galerie", widget: "string", required: false}
      - {label: "Ankündigungsbild", name: "Bild", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
