name: Build and Publish Hugo Site
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Publish Hugo Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source (GIT)
        uses: actions/checkout@v6.0.1
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.154.5'
      - name: Build
        run: hugo --minify --buildFuture
      - name: Upload via SFTP
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'public'
          remoteDir: '.'
          concurrency: 1